import type { MetadataRoute } from 'next';

// Auto-generated by .claude/scripts/lib/emit-sitemap.py during bootstrap
// state-11c post-fan-out (#1387). DO NOT EDIT BY HAND — re-run the script
// after changing experiment.yaml behaviors or dynamic_segments.

function base() {
  return process.env.NEXT_PUBLIC_SITE_URL ?? '';
}

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  const b = base();
  return [
    { url: `${b}/`, lastModified: now, changeFrequency: 'weekly' as const, priority: 1.0 },
    { url: `${b}/audit-file`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7 },
    { url: `${b}/dashboard`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7 },
    { url: `${b}/login`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7 },
    { url: `${b}/notices`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7 },
    { url: `${b}/pricing`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7 },
    { url: `${b}/score`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7 },
    { url: `${b}/sign`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7 },
    { url: `${b}/signup`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7 },
    { url: `${b}/staff`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7 },
    { url: `${b}/v/demo-fixture-variant`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7 },
    { url: `${b}/violations`, lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7 },
  ];
}
